
[general]

	[general.rag_axe]
		rag_axe_alerts = true

	[general.reaper_display]
		reaper_display = false

	[general.cooldown_kick_message]
		cooldown_kick_text = "Cooldown Kicked!"
		cooldown_kick_message = false

[visuals]

	[visuals.session]
		show_minecraft_name_on_screen = false
		display_session_time = false

[blaze]

	[blaze.1_tap]
		blaze_1_tap_helper = false

	[blaze.qol]
		burning_vengance_proc = false

[dungeons]

	[dungeons.general]
		duplicate_class_warning_sound = "note.pling"
		explo_shot_message = false
		show_blood_camp_splits_on_screen = false
		duplicate_class_warning = false
		blood_rush_splits = false
		blood_camp_helper = false
		hide_splits_in_boss = false
		"secret_wayponts_[scuffed_like_bm_but_works]" = false
		auto_open_potion_bag = false
		blood_camp_reminder = false

	[dungeons.party_finder]
		show_mp = false

	[dungeons.invincibility]
		phoenix_text = "Phoenix Procced!"
		bonzo_and_phoenix_messages = false
		bonzo_mask_text = "Bonzo's Mask Procced!"
		disable_during_pre_4 = false

	[dungeons.dungeon_warp_cooldown]
		dungeon_warp_cooldown = false

[location_messages]

	[location_messages.general]
		location_notification_sound = "note.harp"
		location_notifications = false

	[location_messages.location_messages]
		ss_nearby_message = false
		pre_enter_3_nearby_message = false
		pre_enter_2_nearby_message = false
		insta_3_nearby_message = false
		inside_tunnel_message = false
		at_core_message = false

[required]

	[required.api]
		vaje_web_server_communication = true

["f7/m7"]

	["f7/m7".general]
		crystal_spawn_timer = false
		crystal_place_timer = false
		dragon_spawn_timer = false
		predev_timer = false
		healer_debuff_team = 0

	["f7/m7".phase_3]
		only_hide_players_after_leaping = false
		goldor_tick_timer = false
		p3_start_timer = false
		hide_players_in_p3 = false
		terminal_timestamps = false

	["f7/m7".relics]
		relic_spawn_timer = false
		relic_spawn_timer_amount = "42"
		show_every_relic = false
		show_relic_pick_up_time = false
		relic_timer = false

